# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2MdwnMsH6Iwno0R6QaElfaGaPrOLgBC
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# 
# st.title("Data200 Project Dashboard")
# 
# st.header("Upload Dataset")
# 
# uploaded_file = st.file_uploader("Choose a CSV file")
# 
# if uploaded_file is not None:
#     df = pd.read_csv(uploaded_file)
# 
#     st.subheader("Dataset Preview")
#     st.write(df.head())
# 
#     st.subheader("Basic Statistics")
#     st.write(df.describe())
# 
#     st.subheader("Column Selection for Plot")
#     column = st.selectbox("Select column", df.columns)
# 
#     st.line_chart(df[column])